### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by paulogr** [calendee/ionic-leafletjs-map-demo#1]
When I try to add platform android or the cordova geolocation plugin I got this message:

"Current working directory is not a Cordova-based project."

I didn´t see in your demo project files like packages.json or ionic.project...

**Comment by calendee** [comment]
If you cloned it directly, then this will not work.  To make it an ionic project, you need to follow the instructions in the README.  

```
ionic start myMapDemo https://github.com/calendee/ionic-leafletjs-map-demo
```

That will create an Ionic app from this GitHub repo.  Then, you can do whatever you'd like to it.

**Comment by panjos** [comment]
hi and thnks for this example it helped with a project im working on,sory for posting here but couldnt find a mail or something on http://calendee.com/ , how could we add directions from saved location to current location?  that  would be a cool new feauture id be gratefull if u got an idea where i sould look to try to do just that :)

**Comment by calendee** [comment]
No idea on how to do directions.  This was literally the first time I've ever worked with maps.
