### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LearningTools** [calendee/ionic-leafletjs-map-demo#2]
Hi I am using your repository and want to know 2 things,
1. I want to show all coordinates that are in the factory with each market on the same map
2. I also want to add a map of MapBox,

greetings you are well

(my English is not very good)

::::::::
Spanish
::::::::
Hola estoy usando su repositorio y quiero saber 2 cosas,
1. Quiero mostrar todas las coordenadas que están en la fábrica con cada mercado en el mismo mapa
2. Yo también quiero añadir un mapa de MapBox,

saludos estás bien

(mi Inglés no es muy bueno)

**Comment by calendee** [comment]
I apologize for taking so long to get back to you.  You can have additional markers on the map by simply adding to the markers object.

```
$scope.map.markers.a = {
	lat : 33.001,
	lng : 33.001,
	message : 'Location A'
};

$scope.map.markers.b = {
	lat : 32.001,
	lng : 32.001,
	message : 'Location B'
};
```

I'm not familiar with MapBox so you'll need to check them out yourself.

**Comment by karna41317** [comment]
Hi, 

how can i fix above problem if i get locations from rest API, 
How do you add different marker-icons for all these locations.

**Comment by calendee** [comment]
See the answer above.  When you get new markers from any source, you just update `$scope.map.markers`.  Example:

```
$scope.map.markers.newIdFromApi = {
    lat : 32.001,
    lng : 32.001,
    message : 'Location X'
};
```

**Comment by karna41317** [comment]
Hi, 

Thanks for your time, I managed to add all markers. Also i tried to add a link to to Location X , but click does not does not seems to fired. Any clue ? 

My approach is something like this: 
      var location = LocationsService.savedLocations;
      var markers = {};
      angular.forEach(location, function(value, key) {
        markers[location[key].ao] = {
          lat: value.lat,
          lng: value.lng,
          icon:value.icon,
          focus: false,
          draggable: false,
          message: '<span ng-click="openView()">' + value.name + '</span>',
          getMessageScope: function() {return $scope; }
          clickable:true
        }
      });
      $scope.map.markers = markers;
    };

$scope.openView = function (){
   alert('im clicked');
}

Thanks in advance

**Comment by karna41317** [comment]
Hej , its solved now.

**Comment by LearningTools** [comment]
hello, as I can show the locations with firebase

**Comment by calendee** [comment]
Firebase is sort of out of the scope of this demo and would really need to be a completely different issue anyway.  In any case, just use Firebase's "child_added" event to know when locations are added.  Then, iterate through the marked and add them to the map like the samples above.
