### ISSUE TITLE
Base map is blank on android device

### ISSUE THREAD

**Issue by hy9be** [calendee/ionic-leafletjs-map-demo#4]
It is working fine when debugging with Chrome browser. But the base map becomes blank if I run the app on android device.

**Comment by calendee** [comment]
It's running just fine on Android 4.4.2 and 4.4.3 on two different devices for me locally.

Have you tried to debug it?  If you use GapDebug, you'll be able to inspect the app quite easily.

**Comment by hy9be** [comment]
I debugged it and found those base map http requests got 404 response. 

I solved the issue by:
1. Add the whitelist plugin: cordova plugin add https://github.com/apache/cordova-plugin-whitelist.git
2. And update the config.xml with:
  <access origin="*"/>
  <allow-intent href="*"/>
  <allow-navigation href="*"/>

It looks sth blocked network requests.
I am on Android 5.0 btw.

**Comment by kitolog** [comment]
Thank you very much for problem solving!
